var missions = [
	"My cat is stuck in a tree. Can you help me?",
	"My dog is stuck in a tree. Can you help me?",
	"My house is on fire! Help me put it out!",
	"My son is missing. I need you to help me find him.",
	"THE STORE IS ON FIRE! We need to save it!",
	"My kid fell into the river! Help me get him out!",
	"Holy smokes! A bear is in the village. Get him to leave with by luring him out with food.",
	"A cougar just breached the village boundary! Lure him away with some food from the store.",
	"Brr, I don't have a house to go into in this cold. Can you take me to one?",
	"I'm gravely sick but I don't have medicine. Would you borrow some for me?",
	"My boy is about to fall out of a tree!  Please catch him!",
	"I can't start a fire.  Please bring my some wood from the forest.",
	"Go give the patients at the hospital some flowers from the store.",
	"I need help harvesting my crops before they wilt.",
	"Enemy knights have entered the village. Find someone who can chase them out!",
	"The store is running out of food, can you donate some? The farmer probably has some to spare.",
	"Please, I can't open the door. Push me over to it.",
	"Donate an organ for the sick at the hospital.",
	"Please donate money to the poor. Do you have some to spare?",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	""
];